openapi: '3.0.0'
info:
  version: '0.1.1'
  title: BioLink API
  description: >-
    API integration layer for linked biological objects.
  termsOfService: https://github.com/monarch-initiative/biolink-api/
  contact:
    name: Chris Mungall
    x-role: responsible developer
    email: cjm@berkeleybop.org
    x-id:
      - 'https://orcid.org/0000-0002-6601-2165'
      - 'https://github.com/cmungall'
servers:
  - url: 'https://api.monarchinitiative.org/api'
    description: 'Production server'
tags:
  - name: disease
  - name: gene
  - name: phenotype
  - name: annotation
  - name: query
  - name: translator
paths:
  '/bioentity/phenotype/{phenotypeid}':
    get:
      summary: 'Returns phenotype label'
      parameters:
        - name: phenotypeid
          in: path
          description: >-
            CURIE identifier of phenotype, e.g. HP:000001. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/hp/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/hp/'
              template: /bioentity/phenotype/HP:{phenotypeid}
      responses:
        '200':
          description: 'phenotype label'
          x-responseValueType:
            - path: objects
              valueType: 'http://biothings.io/explorer/vocab/terms/phenotype-name/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolink_phenotype_label.json'
  '/bioentity/disease/{diseaseid}':
    get:
      summary: 'Returns phenotype label'
      parameters:
        - name: diseaseid
          in: path
          description: >-
            CURIE identifier of diseae, e.g. MONDO:00001. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/mondo/'
            - 'http://identifiers.org/omim.disease/'
            - 'http://identifiers.org/doid/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/mondo/'
              template: /bioentity/disease/MONDO:{diseaseid}
            - valueType: 'http://identifiers.org/omim.disease/'
              template: /bioentity/disease/OMIM:{diseaseid}
            - valueType: 'http://identifiers.org/doid/'
              template: /bioentity/disease/DOID:{diseaseid}
      responses:
        '200':
          description: 'disease label'
          x-responseValueType:
            - path: objects
              valueType: 'http://biothings.io/explorer/vocab/terms/disease-name/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolink_disease_label.json'
  '/bioentity/gene/{geneid}/expression/anatomy':
    get:
      summary: 'Returns anatomy associated with a gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/expression/anatomy?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType: 'http://identifiers.org/uberon/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolink_gene_anatomy.json'
  '/bioentity/disease/{diseaseid}/genes':
    get:
      summary: 'Returns genes associated with a disease'
      parameters:
        - name: diseaseid
          in: path
          description: >-
            CURIE identifier of disease, e.g. OMIM:605543, DOID:678. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/omim.disease/'
            - 'http://identifiers.org/doid/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/omim.disease/'
              template: /bioentity/disease/OMIM:{diseaseid}/genes?fetch_objects=true&rows=250
            - valueType: 'http://identifiers.org/doid/'
              template: /bioentity/disease/DOID:{diseaseid}/genes?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType: "http://identifiers.org/hgnc/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_disease_gene.json"
  '/bioentity/disease/{diseaseid}/phenotypes':
    get:
      summary: 'Returns phenotypes associated with a disease'
      parameters:
        - name: diseaseid
          in: path
          description: >-
            CURIE identifier of disease, e.g. OMIM:605543, DOID:678. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/omim.disease/'
            - 'http://identifiers.org/doid/'
            - 'http://identifiers.org/orphanet/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/omim.disease/'
              template: /bioentity/disease/OMIM:{diseaseid}/phenotypes/?fetch_objects=true&rows=250
            - valueType: 'http://identifiers.org/orphanet/'
              template: /bioentity/disease/Orphanet:{diseaseid}/phenotypes/?fetch_objects=true&rows=250
            - valueType: 'http://identifiers.org/doid/'
              template: /bioentity/disease/DOID:{diseaseid}/phenotypes/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType: "http://identifiers.org/hp/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_disease_phenotype.json"
  '/bioentity/gene/{geneid}/homologs':
    get:
      summary: 'Returns homologs for a gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/homologs/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: edge.obj
              valueType: 'http://identifiers.org/mgi/'
            - path: edge.obj
              valueType: 'http://identifiers.org/zfin/'
            - path: edge.obj
              valueType: 'http://identifiers.org/hgnc/'
            - path: edge.obj
              valueType: 'http://identifiers.org/flybase/'
            - path: edge.obj
              valueType: 'http://identifiers.org/xenbase/'
            - path: edge.obj
              valueType: 'http://identifiers.org/rgd/'
            - path: edge.obj
              valueType: 'http://identifiers.org/sgd/'
          x-JSONLDContext: "biolink/jsonld_context/biolink_gene_homolog.json"
  '/bioentity/gene/{geneid}/interactions':
    get:
      summary: 'Returns interactions for a gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/hgnc/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/interactions/?fetch_objects=true&rows=250
            - valueType: 'http://identifiers.org/hgnc/'
              template: /bioentity/gene/HGNC:{geneid}/interactions/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/hgnc/"
            - path: objects
              valueType: "http://identifiers.org/mgi/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_gene_interaction.json"
  '/bioentity/gene/{geneid}/phenotypes':
    get:
      summary: 'Returns phenotypes associated with gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/hgnc/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/phenotypes
            - valueType: 'http://identifiers.org/hgnc/'
              template: /bioentity/gene/HGNC:{geneid}/phenotypes
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/hp/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_gene_phenotype.json"
  '/bioentity/gene/{geneid}/pathways':
    get:
      summary: 'Returns pathways associated with gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/hgnc/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/pathways/?fetch_objects=true&rows=250
            - valueType: 'http://identifiers.org/hgnc/'
              template: /bioentity/gene/HGNC:{geneid}/pathways/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/reactome.pathway/"
            - path: objects
              valueType: "http://identifiers.org/kegg.pathway/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_gene_pathway.json"
  '/bioentity/pathway/{pathwayid}/genes':
    get:
      summary: 'Returns genes associated with a pathway'
      parameters:
        - name: pathwayid
          in: path
          description: >-
            CURIE any pathway element. E.g. REACT:R-HSA-5387390
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/reactome/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/reactome/'
              template: /bioentity/pathway/REACT:{pathwayid}/genes/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/hgnc/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_pathway_gene.json"
  '/bioentity/variant/{variantid}/genes':
    get:
      summary: 'Returns genes associated with a variant'
      parameters:
        - name: variantid
          in: path
          description: >-
            CURIE identifier of variant, e.g. ZFIN:ZDB-ALT-010427-8, ClinVarVariant:39783
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/clinvar/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/clinvar/'
              template: /bioentity/variant/ClinVarVariant:{variantid}/genes/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/hgnc/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_variant_gene.json"
  '/bioentity/anatomy/{anatomyid}/genes':
    get:
      summary: 'Returns genes associated with an anatomy'
      parameters:
        - name: anatomyid
          in: path
          description: >-
            CURIE identifier of anatomy, e.g. UBERON:0002037
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/uberon/'
            - 'http://identifiers.org/cl/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/uberon/'
              template: /bioentity/anatomy/UBERON:{anatomyid}/genes/?fetch_objects=true&rows=250
            - valueType: 'http://identifiers.org/cl/'
              template: /bioentity/anatomy/CL:{anatomyid}/genes/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/hgnc/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_anatomy_gene.json"
  '/bioentity/phenotype/{phenotypeid}/anatomy':
    get:
      summary: 'Returns genes associated with an anatomy'
      parameters:
        - name: phenotypeid
          in: path
          description: >-
            CURIE identifier of phenotype, e.g. HP:0000003
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/hp/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/hp/'
              template: /bioentity/phenotype/HP:{phenotypeid}/anatomy/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/uberon/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_phenotype_anatomy.json"
  '/bioentity/gene/{geneid}/diseases':
    get:
      summary: 'Returns diseases associated with a gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:1017
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/hgnc/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/diseases/?fetch_objects=true&rows=200
            - valueType: 'http://identifiers.org/hgnc/'
              template: /bioentity/gene/HGNC:{geneid}/diseases/?fetch_objects=true&rows=250
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType:  "http://identifiers.org/mondo/"
          x-JSONLDContext: "biolink/jsonld_context/biolink_gene_disease.json"