openapi: '3.0.0'
info:
  version: '3.0'
  title: MyGene.info API
  description: >-
    Documentation of the MyGene.info Gene Query web services. Learn more about
    [MyGene.info](http://mygene.info/)
  termsOfService: http://mygene.info/terms/
  contact:
    name: Chunlei Wu
    x-role: responsible developer
    email: help@mygene.info
    x-id:
      - 'http://orcid.org/0000-0002-2629-6124'
      - 'https://github.com/newgene'
servers:
  - url: 'http://mygene.info/v3'
    description: 'Production server'
tags:
  - name: gene
  - name: annotation
  - name: query
  - name: translator
paths:
  /querygene:
    get:
      summary: 'Make gene query and return matching gene hits'
      parameters:
        - name: geneid
          in: path
          description: >-
            Query string. Examples "CDK2", "NM_052827", "204639_at". The
            detailed query syntax can be found at
            http://docs.mygene.info/en/latest/doc/query_service.html
          required: true
          x-valueType:
            - 'http://identifiers.org/hgnc.symbol/'
            - 'http://identifiers.org/refseq/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/hgnc.symbol/'
              template: /query?q=symbol:{geneid}&size=100
            - valueType: 'http://identifiers.org/refseq/'
              template: /query?q=refseq.genomic:{geneid}&size=100
          schema:
            type: string
      responses:
        '200':
          description: 'A query response object with "hits" property'
          x-responseValueType:
            - path: hits.entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
          x-JSONLDContext:
            'mygene.info/jsonld_context/mygene_query_object.json'
  /querygeneproduct:
    get:
      summary: 'Make gene query and return matching gene hits'
      parameters:
        - name: geneproductid
          in: path
          description: >-
            Query string. Examples "CDK2", "NM_052827", "204639_at". The
            detailed query syntax can be found at
            http://docs.mygene.info/en/latest/doc/query_service.html
          required: true
          x-valueType:
            - 'http://identifiers.org/unigene/'
            - 'http://identifiers.org/uniprot/'
            - 'http://identifiers.org/pdb/'
            - 'http://identifiers.org/ensembl.protein/'
            - 'http://identifiers.org/ensembl.transcript/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/unigene/'
              template: /query?q=unigene:{geneproductid}&size=100
            - valueType: 'http://identifiers.org/uniprot/'
              template: /query?q=uniprot.Swiss-Prot:{geneproductid}&size=100
            - valueType: 'http://identifiers.org/pdb/'
              template: /query?q=pdb:{geneproductid}&size=100
            - valueType: 'http://identifiers.org/ensembl.protein/'
              template: /query?q=ensembl.protein:{geneproductid}&size=100
            - valueType: 'http://identifiers.org/ensembl.transcript/'
              template: /query?q=ensembl.transcript:{geneproductid}&size=100
          schema:
            type: string
      responses:
        '200':
          description: 'A query response object with "hits" property'
          x-responseValueType:
            - path: hits.entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
          x-JSONLDContext:
            'mygene.info/jsonld_context/mygene_query_object.json'
  /querypathway:
    get:
      summary: 'Make gene query and return matching gene hits'
      parameters:
        - name: pathwayid
          in: path
          description: >-
            Query string. Examples "CDK2", "NM_052827", "204639_at". The
            detailed query syntax can be found at
            http://docs.mygene.info/en/latest/doc/query_service.html
          required: true
          x-valueType:
            - 'http://identifiers.org/biocarta.pathway/'
            - 'http://identifiers.org/kegg.pathway/'
            - 'http://identifiers.org/wikipathways/'
            - 'http://identifiers.org/pharmgkb.pathways/'
            - 'http://identifiers.org/reactome.pathway/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/biocarta.pathway/'
              template: /query?q=pathway.biocarta.id:{pathwayid}&size=100
            - valueType: 'http://identifiers.org/kegg.pathway/'
              template: /query?q=pathway.kegg.id:{pathwayid}&size=100
            - valueType: 'http://identifiers.org/wikipathways/'
              template: /query?q=pathway.wikipathways.id:{pathwayid}&size=100
            - valueType: 'http://biothings.io/explorer/vocab/terms/pharmgkb.pathway/'
              template: /query?q=pathway.pharmgkb.id:{pathwayid}&size=100
            - valueType: 'http://identifiers.org/reactome.pathway/'
              template: /query?q=pathway.reactome.id:{pathwayid}&size=100
          schema:
            type: string
      responses:
        '200':
          description: 'A query response object with "hits" property'
          x-responseValueType:
            - path: hits.entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
          x-JSONLDContext:
            'mygene.info/jsonld_context/mygene_query_pathway.json'
  /querygo:
    get:
      summary: 'Make gene query and return matching gene hits'
      parameters:
        - name: goid
          in: path
          description: >-
            Query string. Examples "CDK2", "NM_052827", "204639_at". The
            detailed query syntax can be found at
            http://docs.mygene.info/en/latest/doc/query_service.html
          required: true
          x-valueType:
            - 'http://identifiers.org/go/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/go/'
              template: /query?q=GO:{goid}&size=500
          schema:
            type: string
      responses:
        '200':
          description: 'A query response object with "hits" property'
          x-responseValueType:
            - path: hits.entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
          x-JSONLDContext:
            'mygene.info/jsonld_context/mygene_query_pathway.json'
  '/gene/{geneid}':
    get:
      summary: 'For a given gene id, return the matching gene object'
      parameters:
        - name: geneid
          in: path
          description: >-
            Entrez or Ensembl gene id, e.g., 1017, ENSG00000170248. A retired
            Entrez Gene id works too if it is replaced by a new one, e.g.,
            245794
          required: true
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/ensembl.gene/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /gene/{geneid}
            - valueType: 'http://identifiers.org/ensembl.gene/'
              template: /gene/{geneid}
          schema:
            type: string
      responses:
        '200':
          description: 'A gene object'
          x-responseValueType:
            - path: symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
            - path: umls.cui
              valueType: 'http://identifiers.org/umls.gene/'
            - path: unigene
              valueType: 'http://identifiers.org/unigene/'
            - path: uniprot.Swiss-Prot
              valueType: 'http://identifiers.org/uniprot/'
            - path: pdb
              valueType: 'http://identifiers.org/pdb/'
            - path: pathway.biocarta.id
              valueType: 'http://identifiers.org/biocarta.pathway/'
            - path: pathway.kegg.id
              valueType: 'http://identifiers.org/kegg.pathway/'
            - path: pathway.reactome.id
              valueType: 'http://identifiers.org/reactome.pathway/'
            - path: pathway.wikipathways.id
              valueType: 'http://identifiers.org/wikipathways/'
            - path: pathway.pharmgkb.id
              valueType: 'http://biothings.io/explorer/vocab/terms/pharmgkb.pathway/'
            - path: go.bp.id
              valueType: 'http://identifiers.org/go/'
            - path: ensembl.gene
              valueType: 'http://identifiers.org/ensembl.gene/'
            - path: ensembl.protein
              valueType: 'http://identifiers.org/ensembl.protein/'
            - path: ensembl.transcript
              valueType: 'http://identifiers.org/ensembl.transcript/'
            - path: MIM
              valueType: 'http://identifiers.org/omim.gene/'
            - path: HGNC
              valueType: 'http://identifiers.org/hgnc/'
            - path: miRBase
              valueType: 'http://identifiers.org/mirbase/'
          x-JSONLDContext:
            'mygene.info/jsonld_context/mygene_gene_object.json'
